import { groupMembersByCommittee, withMemberMetadata } from './helpers';
import { Member, MemberInput, TeamSectionData } from './types';

const rawMembers: MemberInput[] = [
  // Executive Committee
  {
    name: 'Chanuka Anjana',
    committee: 'ExCom',
    position: 'CHAIRMAN',
    email: 'chanukaanjana01@gmail.com',
    linkedin: 'https://www.linkedin.com/in/chanukaanjana',
    image: '/team-memebrs/ExCom/Chanuka.png',
    imageScale: 0.92,
    imageTranslateY: '0%',
    imageTranslateX: '0%',
  },
  {
    name: 'Uthsara Manul',
    committee: 'ExCom',
    position: 'VICE CHAIRMAN',
    email: 'uthzaaawim@gmail.com',
    linkedin: 'https://www.linkedin.com/in/uthsara-manul-wimalarathne-b3b91121b',
    image: '/team-memebrs/ExCom/Uthsara.png',
    imageScale: 0.92,
    imageTranslateY: '0%',
    imageTranslateX: '0%',
  },
  {
    name: 'Praveesha De Silva',
    committee: 'ExCom',
    position: 'SECRETARY',
    email: 'praveeshadesilva@gmail.com',
    linkedin: 'https://www.linkedin.com/in/praveesha-de-silva-2a43a9277',
    image: '/team-memebrs/ExCom/Praveesha.png',
    imageScale: 1.08,
    imageTranslateY: '-14%',
    imageTranslateX: '0%',
  },
  {
    name: 'Oshadha Kandamby',
    committee: 'ExCom',
    position: 'TREASURER',
    email: 'kandambyoshadha@gmail.com',
    linkedin: 'https://www.linkedin.com/in/oshadha-kandamby-8a78872a4',
    image: '/team-memebrs/ExCom/Oshadha.png',
    imageScale: 1.0,
    imageTranslateY: '0%',
    imageTranslateX: '0%',
  },
  {
    name: 'Yasiru Nilupul',
    committee: 'ExCom',
    position: 'ASSISTANT SECRETARY',
    email: 'yasiru0254321@gmail.com',
    linkedin: 'https://www.linkedin.com/in/yasiru-wickramage-2b6789387',
    image: '/team-memebrs/ExCom/Yasiru.png',
    imageScale: 0.92,
    imageTranslateY: '0%',
    imageTranslateX: '0%',
  },
  {
    name: 'Ishan Hansaka',
    committee: 'ExCom',
    position: 'WEBMASTER',
    email: 'ishanhansakasilva@gmail.com',
    linkedin: 'https://www.linkedin.com/in/ishanhansakasilva',
    image: '/team-memebrs/ExCom/Ishan.png',
    imageScale: 1.0,
    imageTranslateY: '0%',
    imageTranslateX: '0%',
  },
  {
    name: 'Vindhya Kulasinghe',
    committee: 'ExCom',
    position: 'CHAPTER & AFFINITY GROUP COORDINATOR',
    email: 'vindhyakulasingheieeesb25@gmail.com',
    linkedin: 'https://www.linkedin.com/in/vindhya-kumari-kulasinghe-4a828925b',
    image: '/team-memebrs/ExCom/Vindhya.png',
    imageScale: 1.0,
    imageTranslateY: '0%',
    imageTranslateX: '0%',
  },

  // Logistics Management Committee
  {
    name: 'Ishakya Gamage',
    committee: 'Logistics Management Committee',
    position: 'Committee Lead',
    email: 'ishakyaranhiru@gmail.com',
    linkedin: 'https://www.linkedin.com/in/ishakya-gamage-71765b349',
    image: '/team-memebrs/Leadership Body/Ishakya.png',
    imageScale: 1.2,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Lasan Perera',
    committee: 'Logistics Management Committee',
    position: 'Committee Lead',
    email: 'lasanperera.lsp@gmail.com',
    linkedin: 'https://www.linkedin.com/in/lasan-perera-0881a3280',
    image: '/team-memebrs/Leadership Body/Lasan.png',
    imageScale: 1.3,
    imageTranslateY: '1%',
    imageTranslateX: '4%',
  },
  {
    name: 'Dinesh Dissanayaka',
    committee: 'Logistics Management Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Logistics/Dinesh.png',
    imageScale: 1.4,
    imageTranslateY: '2%',
    imageTranslateX: '-2%',
  },
  {
    name: 'Kushani Umanda',
    committee: 'Logistics Management Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Logistics/Kushani.png',
    imageScale: 1.4,
    imageTranslateY: '4%',
    imageTranslateX: '0%',
  },
  {
    name: 'Nisal Jayaweera',
    committee: 'Logistics Management Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Logistics/Nisal.png',
    imageScale: 1.0,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Sadil Ephraims',
    committee: 'Logistics Management Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Logistics/Ephraims.png',
    imageScale: 1.5,
    imageTranslateY: '2%',
    imageTranslateX: '6%',
  },
  {
    name: 'Devindi Wickramarathna',
    committee: 'Logistics Management Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Logistics/Devindi.png',
    imageScale: 1.4,
    imageTranslateY: '1%',
    imageTranslateX: '-6%',
  },

  // Editorial Committee
  {
    name: 'Imesh Yasindu',
    committee: 'Editorial Committee',
    position: 'Committee Lead',
    email: 'imesh7lk@gmail.com',
    linkedin: 'https://www.linkedin.com/in/imeshmunasinghe/',
    image: '/team-memebrs/Leadership Body/Imesh.png',
    imageScale: 1.4,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Ranudi Namarathna',
    committee: 'Editorial Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Editorial/Ranudi.png',
    imageScale: 1.2,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Kusal Nirukshan Amantha',
    committee: 'Editorial Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Editorial/Kusal.png',
    imageScale: 1.2,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Kamitha Akash',
    committee: 'Editorial Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Editorial/Kamitha.png',
    imageScale: 1.4,
    imageTranslateY: '2%',
    imageTranslateX: '2%',
  },
  {
    name: 'Jithmini Munasinghe',
    committee: 'Editorial Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Editorial/Jithmini.png',
    imageScale: 1.2,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Asheni Bandara',
    committee: 'Editorial Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Editorial/Asheni.png',
    imageScale: 1.0,
    imageTranslateY: '2%',
    imageTranslateX: '-5%',
  },
  {
    name: 'Senaya Bandara',
    committee: 'Editorial Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Editorial/Senaya.png',
    imageScale: 1.0,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },

  // Design Committee
  {
    name: 'Sahas Samuditha',
    committee: 'Design Committee',
    position: 'Committee Lead',
    email: 'sahas.samuditha@gmail.com',
    linkedin: 'https://www.linkedin.com/in/sahas-samuditha',
    image: '/team-memebrs/Leadership Body/Sahas.png',
    imageScale: 1.2,
    imageTranslateY: '2%',
    imageTranslateX: '5%',
  },
  {
    name: 'Seniya Amarakoon',
    committee: 'Design Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Design/Seniya.png',
    imageScale: 1.3,
    imageTranslateY: '2%',
    imageTranslateX: '5%',
  },
  {
    name: 'Sineth Wickramaratna',
    committee: 'Design Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Design/Sineth.png',
    imageScale: 1.3,
    imageTranslateY: '2%',
    imageTranslateX: '11%',
  },
  {
    name: 'Minuka De Silva',
    committee: 'Design Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Design/Minuka.png',
    imageScale: 2.0,
    imageTranslateY: '-28%',
    imageTranslateX: '0%',
  },
  {
    name: 'Thisul Dulneth',
    committee: 'Design Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Design/Thisul.png',
    imageScale: 1.0,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },

  // Publicity Committee
  {
    name: 'Thamalu Bambaravanage',
    committee: 'Publicity Committee',
    position: 'Committee Lead',
    email: 'thamaludinu@gmail.com',
    linkedin: 'https://www.linkedin.com/in/thamalu',
    image: '/team-memebrs/Leadership Body/Thamalu.png',
    imageScale: 1.4,
    imageTranslateY: '2%',
    imageTranslateX: '-4%',
  },
  {
    name: 'Buddhima Gayashan',
    committee: 'Publicity Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Publicity/Buddhima.png',
    imageScale: 1.0,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Dulmi Jayasooriya',
    committee: 'Publicity Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Publicity/Dulmi.png',
    imageScale: 1.7,
    imageTranslateY: '1%',
    imageTranslateX: '20%',
  },
  {
    name: 'Adeesha Surawiman',
    committee: 'Publicity Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Publicity/Adeesha.png',
    imageScale: 1.8,
    imageTranslateY: '2%',
    imageTranslateX: '-13%',
  },
  {
    name: 'Rashmika Dilshan',
    committee: 'Publicity Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Publicity/Rashmika.png',
    imageScale: 1.3,
    imageTranslateY: '2%',
    imageTranslateX: '8%',
  },
  {
    name: 'Sadeepa Herath',
    committee: 'Publicity Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Publicity/Sadeepa.png',
    imageScale: 1.4,
    imageTranslateY: '2%',
    imageTranslateX: '-3%',
  },
  {
    name: 'Sandali Sathsarani',
    committee: 'Publicity Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Publicity/Sandali.png',
    imageScale: 1.1,
    imageTranslateY: '3%',
    imageTranslateX: '5%',
  },
  {
    name: 'Janidu Janadara',
    committee: 'Publicity Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Publicity/Janindu.png',
    imageScale: 1.0,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Chamoth Sandeepa',
    committee: 'Publicity Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Publicity/Chamoth.png',
    imageScale: 1.1,
    imageTranslateY: '2%',
    imageTranslateX: '3%',
  },

  // Volunteer Management Committee
  {
    name: 'Gishan Chamith',
    committee: 'Volunteer Management Committee',
    position: 'Committee Lead',
    email: 'gishanchamith77@gmail.com',
    linkedin: 'https://www.linkedin.com/in/gishan-chamith-66b49b340',
    image: '/team-memebrs/Leadership Body/Gishan.png',
    imageScale: 1.1,
    imageTranslateY: '1%',
    imageTranslateX: '-5%',
  },
  {
    name: 'Randi Kaweesha',
    committee: 'Volunteer Management Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Volunteer/Randi.png',
    imageScale: 1.2,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Gayangi Devindi',
    committee: 'Volunteer Management Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Volunteer/Gayangi.png',
    imageScale: 1.1,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Sandakelum Dissanayake',
    committee: 'Volunteer Management Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Volunteer/Sandakelum.png',
    imageScale: 1.0,
    imageTranslateY: '2%',
    imageTranslateX: '3%',
  },
  {
    name: 'Thisandi Rajapaksha',
    committee: 'Volunteer Management Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Volunteer/Thisandi.png',
    imageScale: 1.0,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Janiru Dewanmith',
    committee: 'Volunteer Management Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Volunteer/Janiru.png',
    imageScale: 1.1,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },

  // Events Committee
  {
    name: 'Hiruna Malavipathirana',
    committee: 'Events Committee',
    position: 'Committee Lead',
    email: 'hirunamalavipathirana.333@gmail.com',
    linkedin: 'https://www.linkedin.com/in/hiruna-malavipathirana-b0904916a',
    image: '/team-memebrs/Leadership Body/Hiruna.png',
    imageScale: 1.1,
    imageTranslateY: '2%',
    imageTranslateX: '5%',
  },
  {
    name: 'Sandali Kadawedduwa',
    committee: 'Events Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Events/Sandali.png',
    imageScale: 1.0,
    imageTranslateY: '1%',
    imageTranslateX: '0%',
  },
  {
    name: 'Dulmini Aththanayaka',
    committee: 'Events Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Events/Dulmini.png',
    imageScale: 1.2,
    imageTranslateY: '1%',
    imageTranslateX: '3%',
  },
  {
    name: 'Nimindu Prishmika',
    committee: 'Events Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Events/Nimindu.png',
    imageScale: 1.5,
    imageTranslateY: '1%',
    imageTranslateX: '-18%',
  },
  {
    name: 'Induru Adeesha',
    committee: 'Events Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Events/Induru.png',
    imageScale: 1.0,
    imageTranslateY: '1%',
    imageTranslateX: '0%',
  },
  {
    name: 'Mindiya Karunasinghe',
    committee: 'Events Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Events/Mindiya.png',
    imageScale: 1.3,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },

  // Finance & IR Committee
  {
    name: 'Yashini Gunasekara',
    committee: 'Finance & IR Committee',
    position: 'Committee Lead',
    email: 'yjgunasekara@gmail.com',
    linkedin: 'https://www.linkedin.com/in/yashini-gunasekara-773b59313',
    image: '/team-memebrs/Leadership Body/Yashini.png',
    imageScale: 1.1,
    imageTranslateY: '1%',
    imageTranslateX: '0%',
  },
  {
    name: 'Inuka Jithmal',
    committee: 'Finance & IR Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Finance/Inuka.png',
    imageScale: 1.1,
    imageTranslateY: '2%',
    imageTranslateX: '2%',
  },
  {
    name: 'Randula Wanniarachchi',
    committee: 'Finance & IR Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Finance/Randula.png',
    imageScale: 1.2,
    imageTranslateY: '1%',
    imageTranslateX: '0%',
  },
  {
    name: 'Sanduni Gamage',
    committee: 'Finance & IR Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Finance/Sanduni.png',
    imageScale: 1.1,
    imageTranslateY: '0%',
    imageTranslateX: '0%',
  },
  {
    name: 'Suvindu Ranchigoda',
    committee: 'Finance & IR Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Finance/Suvindu.png',
    imageScale: 1.2,
    imageTranslateY: '2%',
    imageTranslateX: '1%',
  },
  {
    name: 'Kumudya Gnanaweera',
    committee: 'Finance & IR Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Finance/Kumudya.png',
    imageScale: 1.1,
    imageTranslateY: '1%',
    imageTranslateX: '-4%',
  },

  // Membership Development Committee
  {
    name: 'Kalana Abeysundara',
    committee: 'Membership Development Committee',
    position: 'Committee Lead',
    email: 'knbabeysundara@gmail.com',
    linkedin: 'https://www.linkedin.com/in/kalana-abeysundara',
    image: '/team-memebrs/Leadership Body/Kalana.png',
    imageScale: 1.2,
    imageTranslateY: '1%',
    imageTranslateX: '0%',
  },
  {
    name: 'Manjari Manesha',
    committee: 'Membership Development Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Membership/Manjari.png',
    imageScale: 1.0,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Oshini Ravintha',
    committee: 'Membership Development Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Membership/Oshini.png',
    imageScale: 1.0,
    imageTranslateY: '1%',
    imageTranslateX: '-2%',
  },
  {
    name: 'Hasaruvi Kodithuwakku',
    committee: 'Membership Development Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Membership/Hasaruvi.png',
    imageScale: 1.2,
    imageTranslateY: '1%',
    imageTranslateX: '1%',
  },
  {
    name: 'Kevin Ambrose',
    committee: 'Membership Development Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Membership/Kevin.png',
    imageScale: 1.2,
    imageTranslateY: '2%',
    imageTranslateX: '3%',
  },
  {
    name: 'Umesh Bandara',
    committee: 'Membership Development Committee',
    position: 'Committee Member',
    image: '/team-memebrs/Membership/Umesh.png',
    imageScale: 1.2,
    imageTranslateY: '0%',
    imageTranslateX: '-2%',
  },

  // Leadership Body (Summary entries for Leads section)
  {
    name: 'Hiruna Malavipathirana',
    committee: 'Leadership Body',
    position: 'EVENTS COMMITTEE LEAD',
    email: 'hirunamalavipathirana.333@gmail.com',
    linkedin: 'https://www.linkedin.com/in/hiruna-malavipathirana-b0904916a',
    image: '/team-memebrs/Leadership Body/Hiruna.png',
    imageScale: 1.1,
    imageTranslateY: '2%',
    imageTranslateX: '5%',
  },
  {
    name: 'Sahas Samuditha',
    committee: 'Leadership Body',
    position: 'DESIGN COMMITTEE LEAD',
    email: 'sahas.samuditha@gmail.com',
    linkedin: 'https://www.linkedin.com/in/sahas.samuditha',
    image: '/team-memebrs/Leadership Body/Sahas.png',
    imageScale: 1.2,
    imageTranslateY: '2%',
    imageTranslateX: '5%',
  },
  {
    name: 'Yashini Gunasekara',
    committee: 'Leadership Body',
    position: 'FINANCE & IR COMMITTEE LEAD',
    email: 'yjgunasekara@gmail.com',
    linkedin: 'https://www.linkedin.com/in/yashini-gunasekara-773b59313',
    image: '/team-memebrs/Leadership Body/Yashini.png',
    imageScale: 1.1,
    imageTranslateY: '1%',
    imageTranslateX: '0%',
  },
  {
    name: 'Lasan Perera',
    committee: 'Leadership Body',
    position: 'LOGISTIC MANAGEMENT COMMITTEE CO-LEAD',
    email: 'lasanperera.lsp@gmail.com',
    linkedin: 'https://www.linkedin.com/in/lasan-perera-0881a3280',
    image: '/team-memebrs/Leadership Body/Lasan.png',
    imageScale: 1.3,
    imageTranslateY: '1%',
    imageTranslateX: '4%',
  },
  {
    name: 'Ishakya Gamage',
    committee: 'Leadership Body',
    position: 'LOGISTICS MANAGEMENT COMMITTEE CO-LEAD',
    email: 'ishakyaranhiru@gmail.com',
    linkedin: 'https://www.linkedin.com/in/ishakya-gamage-71765b349',
    image: '/team-memebrs/Leadership Body/Ishakya.png',
    imageScale: 1.2,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Thamalu Bambaravanage',
    committee: 'Leadership Body',
    position: 'PUBLICITY COMMITTEE LEAD',
    email: 'thamaludinu@gmail.com',
    linkedin: 'https://www.linkedin.com/in/thamalu',
    image: '/team-memebrs/Leadership Body/Thamalu.png',
    imageScale: 1.4,
    imageTranslateY: '2%',
    imageTranslateX: '-4%',
  },
  {
    name: 'Imesh Yasindu',
    committee: 'Leadership Body',
    position: 'EDITORIAL COMMITTEE LEAD',
    email: 'imesh7lk@gmail.com',
    linkedin: 'https://www.linkedin.com/in/imeshmunasinghe',
    image: '/team-memebrs/Leadership Body/Imesh.png',
    imageScale: 1.4,
    imageTranslateY: '2%',
    imageTranslateX: '0%',
  },
  {
    name: 'Gishan Chamith',
    committee: 'Leadership Body',
    position: 'VOLUNTEER MANAGEMENT COMMITTEE LEAD',
    email: 'gishanchamith77@gmail.com',
    linkedin: 'https://www.linkedin.com/in/gishan-chamith-66b49b340',
    image: '/team-memebrs/Leadership Body/Gishan.png',
    imageScale: 1.1,
    imageTranslateY: '1%',
    imageTranslateX: '-5%',
  },
  {
    name: 'Kalana Abeysundara',
    committee: 'Leadership Body',
    position: 'MEMBERSHIP DEVELOPMENT COMMITTEE LEAD',
    email: 'knbabeysundara@gmail.com',
    linkedin: 'https://www.linkedin.com/in/kalana-abeysundara',
    image: '/team-memebrs/Leadership Body/Kalana.png',
    imageScale: 1.2,
    imageTranslateY: '1%',
    imageTranslateX: '0%',
  },
  {
    name: 'Banula Balasooriya',
    committee: 'Leadership Body',
    position: 'RoboRoarZ 2025 CHAIRPERSON',
    email: 'banulabalasooriya@gmail.com',
    linkedin: 'https://www.linkedin.com/in/banula-balasooriya-43897239a',
    image: '/team-memebrs/Leadership Body/Banula.png',
    imageScale: 1.1,
    imageTranslateY: '3%',
    imageTranslateX: '0%',
  },
];

export const teamMembers: Member[] = rawMembers.map(withMemberMetadata);

export const teamSections: TeamSectionData[] = groupMembersByCommittee(teamMembers);
